### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by ignoramous** [Neuron-Grid/Rethink_DNS_JP_version#3]
Hi there,

Thanks for the translation. The current readme was woefully out-of-date, and so, I updated it just today to reflect the current state of the codebase.

Here's the new one: https://github.com/serverless-dns/serverless-dns/commit/191b50c95/README.md

Of course, this issue isn't a directive to translate, but a mere FYI. (:

**Comment by Neuron-Grid** [comment]
@ignoramous 
Thank you very much.
I will start the translation work within 10 days.
